networks:
  default:
    external: true
    name: traefik

services:
  fe:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    labels:
      traefik.enable: true
      traefik.http.services.home.loadbalancer.server.port: 80
      traefik.http.routers.home.rule: Host(`ygh.kr`) || Host(`www.ygh.kr`)
      traefik.http.routers.home.entrypoints: websecure
      traefik.http.routers.home.tls: true
      traefik.http.routers.home.tls.certresolver: letsencrypt
      traefik.http.routers.home.middlewares: redirect-www
      traefik.http.middlewares.redirect-www.redirectregex.permanent: true
      traefik.http.middlewares.redirect-www.redirectregex.regex: ^https://ygh.kr/(.*)
      traefik.http.middlewares.redirect-www.redirectregex.replacement: https://www.ygh.kr/$${1}
    configs:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf

configs:
  nginx-config:
    content: |
      server {
        listen 80;
        server_name localhost;
        root /usr/share/nginx/html;
        
        location ~* \.(svg|png|xml|json|html|css|js)$ {
          try_files $$uri $$uri/ =404;
        }
        location = / { index index.html; }
        location / { return 301 /; }
      }
