networks:
  default:
    external: true
    name: npm

services:
  fe:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - .:/usr/share/nginx/html
    entrypoint:
      - sh
      - -euc
      - |
        cat <<EOF > /etc/nginx/conf.d/default.conf
        server {
          listen 80;
          server_name localhost;
          root /usr/share/nginx/html;
          
          location ~* \.(svg|png|xml|html|css|js)$ {
            try_files \$$uri \$$uri/ =404;
          }
          location = / { index index.html; }
          location / { return 301 /; }
        }
        EOF
        nginx -g 'daemon off;'
